defaults:
    -
        scope:
            path: ""
        values:
            cv_file: cv-en-last-update-20-03-14.pdf
            show_hire_me_button: no
            show_testimonials: no
            show_featured_projects: no
            show_blog: no
            show_project_cards: no

